### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'timeout'

### ISSUE THREAD

**Issue by 8Thomas8** [cyr-ius/heatzypy#14]
https://github.com/cyr-ius/heatzypy/blob/13d8a253db411572e8f5041c5161903511d3e05b/heatzypy/auth.py#L58-L65

Ce passage m'a beaucoup gêné pour tester si ma PR faisait quelque chose. A priori `asyncio `n'a plus d'attribut `timeout`. J'avais cette erreur :
```
Traceback (most recent call last):
  File "f:\Projets\heatzypy\example.py", line 47, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "f:\Projets\heatzypy\example.py", line 27, in main
    devices = await api.async_get_devices()
  File "f:\Projets\heatzypy\heatzypy\heatzy.py", line 34, in async_get_devices
    response = await self.async_bindings()
  File "f:\Projets\heatzypy\heatzypy\heatzy.py", line 30, in async_bindings
    return await self.request("bindings")
  File "f:\Projets\heatzypy\heatzypy\auth.py", line 52, in request
    access_token = await self._async_get_token()
  File "f:\Projets\heatzypy\heatzypy\auth.py", line 111, in _async_get_token
    self._access_token = await self.request(
  File "f:\Projets\heatzypy\heatzypy\auth.py", line 58, in request
    async with asyncio.timeout(self._timeout):
AttributeError: module 'asyncio' has no attribute 'timeout'
```

Je ne sais pas si il y a besoin de ton coté mais je l'ai remplacé par ceci pour que ça passe :
```py
response = await asyncio.wait_for(
   self._session.request(
      method,
      f"{HEATZY_API_URL}/{service}",
      **kwargs,
      headers=headers,
      ),
      timeout=self._timeout,
   )
   response.raise_for_status()

   except asyncio.TimeoutError:
      # Handle timeout error here
      _LOGGER.error("Timeout occurred.")
```

**Comment by cyr-ius** [comment]
Tu code à partir de python 3.10,  la fonction a été rajoutée en python 3.11

https://docs.python.org/3/whatsnew/3.11.html

**Comment by 8Thomas8** [comment]
Ok. C'est ce que j'avais cru comprendre mais j'étais avec 3.11 il me semble. Je vais me refaire un setup plus clean pour python et revoir.

Merci.

**Comment by 8Thomas8** [comment]
Mon install était pétée, j'avais 3.10 et 3.11 c'est ok du coup, je ferme.
